export default {
  yup_mixed_invalid_field: 'Este campo é inválido',
  yup_mixed_required_label_field: 'é um campo obrigatório',
  yup_mixed_required_field: 'Este é um campo obrigatório',
  yup_mixed_one_of: 'Este campo deve ter um dos seguintes valores: %{values}',
  yup_mixed_not_one_of:
    'Este campo não pode ter um dos seguintes valores: %{values}',
  yup_string_length: 'Este campo deve ter exatamente %{length} caracteres',
  yup_string_min: 'Este campo deve ter pelo menos %{min} caracteres',
  yup_string_max: 'Este campo deve ter no máximo %{max} caracteres',
  yup_string_email: 'Este campo tem o formato de e-mail inválido',
  yup_string_url: 'Este campo deve ter um formato de URL válida',
  yup_string_trim: 'Este campo não deve conter espaços no início ou no fim',
  yup_string_lowercase: 'Este campo deve estar em maiúsculo',
  yup_string_uppercase: 'Este campo deve estar em minúsculo',
  yup_number_min: 'Este campo deve ter no mínimo %{min}',
  yup_number_max: 'Este campo deve ter no máximo %{max}',
  yup_number_lessThan: 'Este campo deve ser menor que %{less}',
  yup_number_moreThan: 'Este campo deve ser maior que %{more}',
  yup_number_notEqual: 'Este campo não pode ser igual a %{notEqual}',
  yup_number_positive: 'Este campo deve ser um número positivo',
  yup_number_negative: 'Este campo deve ser um número negativo',
  yup_number_integer: 'Este campo deve ser um número inteiro',
  yup_date_min: 'Este campo deve ser maior que a data %{min}',
  yup_date_max: 'Este campo deve ser menor que a data %{max}',
  yup_array_min: 'Este campo deve ter no mínimo %{min} item(s)',
  yup_array_max: 'Este campo deve ter no máximo %{max} item(s)',
};
